## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [1]:
import os
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# 設定 data_path
dir_data = './data/'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [4]:
app_train.shape

(307511, 122)

#### 列出所有欄位

In [5]:
app_train.T

,0,1,2,3,4,5,6,7,8,9,...,307501,307502,307503,307504,307505,307506,307507,307508,307509,307510
SK_ID_CURR,100002,100003,100004,100006,100007,100008,100009,100010,100011,100012,...,456245,456246,456247,456248,456249,456251,456252,456253,456254,456255
TARGET,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
NAME_CONTRACT_TYPE,Cash loans,Cash loans,Revolving loans,Cash loans,Cash loans,Cash loans,Cash loans,Cash loans,Cash loans,Revolving loans,...,Cash loans,Cash loans,Cash loans,Cash loans,Cash loans,Cash loans,Cash loans,Cash loans,Cash loans,Cash loans
CODE_GENDER,M,F,M,F,M,M,F,M,F,M,...,F,F,F,F,F,M,F,F,F,F
FLAG_OWN_CAR,N,N,Y,N,N,N,Y,Y,N,N,...,N,N,N,N,N,N,N,N,N,N
FLAG_OWN_REALTY,Y,N,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,N,Y,Y,Y,N
CNT_CHILDREN,0,0,0,0,0,0,1,0,0,0,...,3,1,0,0,0,0,0,0,0,0
AMT_INCOME_TOTAL,202500,270000,67500,135000,121500,99000,171000,360000,112500,135000,...,81000,94500,112500,153000,112500,157500,72000,153000,171000,157500
AMT_CREDIT,406598,1.2935e+06,135000,312682,513000,490496,1.56073e+06,1.53e+06,1.01961e+06,405000,...,269550,225000,345510,331920,225000,254700,269550,677664,370107,675000
AMT_ANNUITY,24700.5,35698.5,6750,29686.5,21865.5,27517.5,41301,42075,33826.5,20250,...,11871,10620,17770.5,16096.5,22050,27558,12001.5,29979,20205,49117.5
AMT_GOODS_PRICE,351000,1.1295e+06,135000,297000,513000,454500,1.395e+06,1.53e+06,913500,405000,...,225000,225000,247500,225000,225000,225000,225000,585000,319500,675000
NAME_TYPE_SUITE,Unaccompanied,Family,Unaccompanied,Unaccompanied,Unaccompanied,"Spouse, partner",Unaccompanied,Unaccompanied,Children,Unaccompanied,...,Unaccompanied,Unaccompanied,Unaccompanied,Unaccompanied,Unaccompanied,Unaccompanied,Unaccompanied,Unaccompanied,Unaccompanied,Unaccompanied
NAME_INCOME_TYPE,Working,State servant,Working,Working,Working,State servant,Commercial associate,State servant,Pensioner,Working,...,Commercial associate,Working,Commercial associate,Working,Pensioner,Working,Pensioner,Working,Commercial associate,Commercial associate
NAME_EDUCATION_TYPE,Secondary / secondary special,Higher education,Secondary / secondary special,Secondary / secondary special,Secondary / secondary special,Secondary / secondary special,Higher education,Higher education,Secondary / secondary special,Secondary / secondary special,...,Secondary / secondary special,Secondary / secondary special,Higher education,Secondary / secondary special,Secondary / secondary special,Secondary / secondary special,Secondary / secondary special,Higher education,Secondary / secondary special,Higher education
NAME_FAMILY_STATUS,Single / not married,Married,Single / not married,Civil marriage,Single / not married,Married,Married,Married,Married,Single / not married,...,Married,Married,Single / not married,Separated,Single / not married,Separated,Widow,Separated,Married,Married
NAME_HOUSING_TYPE,House / apartment,House / apartment,House / apartment,House / apartment,House / apartment,House / apartment,House / apartment,House / apartment,House / apartment,House / apartment,...,House / apartment,House / apartment,House / apartment,House / apartment,House / apartment,With parents,House / apartment,House / apartment,House / apartment,House / apartment
REGION_POPULATION_RELATIVE,0.018801,0.003541,0.010032,0.008019,0.028663,0.035792,0.035792,0.003122,0.018634,0.019689,...,0.009175,0.010966,0.0228,0.022625,0.0228,0.032561,0.025164,0.005002,0.005313,0.04622
DAYS_BIRTH,-9461,-16765,-19046,-19005,-19932,-16941,-13778,-18850,-20099,-14469,...,-12961,-16063,-11870,-16705,-24384,-9327,-20775,-14966,-11961,-16856
DAYS_EMPLOYED,-637,-1188,-225,-3039,-3038,-1588,-3130,-449,365243,-2019,...,-1046,-8736,-399,-7258,365243,-236,365243,-7921,-4786,-1262
DAYS_REGISTRATION,-3648,-1186,-4260,-9833,-4311,-4970,-1213,-4597,-7427,-14437,...,-1398,-8672,-675,-9798,-7369,-8456,-4388,-6737,-2562,-5128
DAYS_ID_PUBLISH,-2120,-291,-2531,-2437,-3458,-477,-619,-2379,-3514,-3992,...,-3780,-4531,-3936,-259,-2357,-1982,-4090,-5150,-931,-410
OWN_CAR_AGE,NaN,NaN,26,NaN,NaN,NaN,17,8,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLAG_MOBIL,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
FLAG_EMP_PHONE,1,1,1,1,1,1,1,1,0,1,...,1,1,1,1,0,1,0,1,1,1
FLAG_WORK_PHONE,0,0,1,0,0,1,0,1,0,0,...,1,1,0,0,0,0,0,0,0,1
FLAG_CONT_MOBILE,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
FLAG_PHONE,1,1,1,0,0,1,1,0,0,0,...,0,0,0,0,1,0,1,0,0,1
FLAG_EMAIL,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
OCCUPATION_TYPE,Laborers,Core staff,Laborers,Laborers,Core staff,Laborers,Accountants,Managers,NaN,Laborers,...,Low-skill Laborers,Laborers,Core staff,Sales staff,NaN,Sales staff,NaN,Managers,Laborers,Laborers
CNT_FAM_MEMBERS,1,2,1,2,1,2,3,2,2,1,...,5,3,1,1,1,1,1,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DEF_30_CNT_SOCIAL_CIRCLE,2,0,0,0,0,0,0,0,0,0,...,1,0,3,0,0,0,0,0,0,0
OBS_60_CNT_SOCIAL_CIRCLE,2,1,0,2,0,0,1,2,1,2,...,2,0,9,0,0,0,0,6,0,0
DEF_60_CNT_SOCIAL_CIRCLE,2,0,0,0,0,0,0,0,0,0,...,1,0,2,0,0,0,0,0,0,0
DAYS_LAST_PHONE_CHANGE,-1134,-828,-815,-617,-1106,-2536,-1562,-1070,0,-1673,...,-448,-1516,-2315,0,0,-273,0,-1909,-322,-787
FLAG_DOCUMENT_2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_3,1,1,0,1,0,1,0,1,1,0,...,1,1,1,1,0,0,1,1,1,1
FLAG_DOCUMENT_4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
FLAG_DOCUMENT_7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_8,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
FLAG_DOCUMENT_9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_14,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FLAG_DOCUMENT_21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AMT_REQ_CREDIT_BUREAU_HOUR,0,0,0,NaN,0,0,0,0,0,NaN,...,NaN,0,0,NaN,0,NaN,NaN,1,0,0
AMT_REQ_CREDIT_BUREAU_DAY,0,0,0,NaN,0,0,0,0,0,NaN,...,NaN,0,0,NaN,0,NaN,NaN,0,0,0
AMT_REQ_CREDIT_BUREAU_WEEK,0,0,0,NaN,0,0,0,0,0,NaN,...,NaN,0,0,NaN,0,NaN,NaN,0,0,0
AMT_REQ_CREDIT_BUREAU_MON,0,0,0,NaN,0,0,1,0,0,NaN,...,NaN,0,1,NaN,2,NaN,NaN,1,0,2
AMT_REQ_CREDIT_BUREAU_QRT,0,0,0,NaN,0,1,1,0,0,NaN,...,NaN,0,0,NaN,0,NaN,NaN,0,0,0
AMT_REQ_CREDIT_BUREAU_YEAR,1,0,0,NaN,0,1,2,0,1,NaN,...,NaN,1,2,NaN,0,NaN,NaN,1,0,1

#### 截取部分資料

In [6]:
app_train.iloc[:10, :15]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married
5,100008,0,Cash loans,M,N,Y,0,99000.0,490495.5,27517.5,454500.0,"Spouse, partner",State servant,Secondary / secondary special,Married
6,100009,0,Cash loans,F,Y,Y,1,171000.0,1560726.0,41301.0,1395000.0,Unaccompanied,Commercial associate,Higher education,Married
7,100010,0,Cash loans,M,Y,Y,0,360000.0,1530000.0,42075.0,1530000.0,Unaccompanied,State servant,Higher education,Married
8,100011,0,Cash loans,F,N,Y,0,112500.0,1019610.0,33826.5,913500.0,Children,Pensioner,Secondary / secondary special,Married
9,100012,0,Revolving loans,M,N,Y,0,135000.0,405000.0,20250.0,405000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子